#!/bin/bash
# log-work.sh — Mechanically enforced work logging
# Every session MUST call this after meaningful work.
# The daily X content cron reads from this log.
#
# Usage: bash scripts/log-work.sh <category> <summary>
#   category: feature|fix|research|release|discovery|decision
#   summary: One-line description of what was done
#
# Example: bash scripts/log-work.sh feature "Built Process Guardian — 3-layer process management for AI agents"
# Example: bash scripts/log-work.sh research "Found that Kalshi price 0.60-0.70 has 67% win rate vs 3% at 0.85+"
# Example: bash scripts/log-work.sh release "Published openclaw-hardening v1.1 to GitHub"

set -euo pipefail

CATEGORY="${1:-}"
SUMMARY="${2:-}"
TODAY=$(date -u +%Y-%m-%d)
WORK_LOG="/home/clawdbot/clawd/memory/work-log-${TODAY}.md"
NOW=$(date -u +%H:%M)
SESSION="${CLAWDBOT_SESSION_KEY:-unknown}"

if [[ -z "$CATEGORY" || -z "$SUMMARY" ]]; then
    echo "ERROR: Usage: log-work.sh <category> <summary>"
    echo "Categories: feature|fix|research|release|discovery|decision"
    exit 1
fi

# Validate category
VALID_CATEGORIES="feature fix research release discovery decision"
if ! echo "$VALID_CATEGORIES" | grep -qw "$CATEGORY"; then
    echo "ERROR: Invalid category '$CATEGORY'"
    echo "Valid: $VALID_CATEGORIES"
    exit 1
fi

# Create log file with header if it doesn't exist
if [[ ! -f "$WORK_LOG" ]]; then
    cat > "$WORK_LOG" << EOF
# Work Log — ${TODAY}
# Auto-generated by log-work.sh. Used by daily X content cron.
# Format: [HH:MM] (session) [category] summary

EOF
fi

# Append entry
echo "- [${NOW}] (${SESSION}) [${CATEGORY}] ${SUMMARY}" >> "$WORK_LOG"
echo "✅ Logged: [${CATEGORY}] ${SUMMARY}"
