"""
IRS Form 1040 PDF Generator

Generates a simplified Form 1040-style PDF tax return.
This is for informational purposes only - not for actual IRS filing.
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
import io


def generate_form_1040_pdf(tax_data: Dict[str, Any], output_path: str = None) -> bytes:
    """
    Generate a Form 1040-style PDF from tax data.
    
    Args:
        tax_data: Dictionary containing all tax calculation data
        output_path: Optional file path to save PDF (if None, returns bytes)
    
    Returns:
        PDF bytes if output_path is None
    """
    # Create buffer or file
    if output_path:
        buffer = output_path
    else:
        buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=16,
        alignment=TA_CENTER,
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_CENTER,
        textColor=colors.gray,
        spaceAfter=12
    )
    section_style = ParagraphStyle(
        'Section',
        parent=styles['Heading2'],
        fontSize=12,
        spaceBefore=12,
        spaceAfter=6,
        textColor=colors.HexColor('#1e3a5f')
    )
    normal_style = styles['Normal']
    
    # Build document elements
    elements = []
    
    # Header
    elements.append(Paragraph("Form 1040 - U.S. Individual Income Tax Return", title_style))
    elements.append(Paragraph(f"Tax Year {tax_data.get('tax_year', 2024)} | Generated by TaxSnapPro", subtitle_style))
    elements.append(Paragraph(
        "<i>For informational purposes only - Not for IRS submission</i>",
        ParagraphStyle('Disclaimer', parent=normal_style, alignment=TA_CENTER, textColor=colors.red, fontSize=9)
    ))
    elements.append(Spacer(1, 12))
    
    # Filing Status
    filing_status = tax_data.get('filing_status', 'single').replace('_', ' ').title()
    elements.append(Paragraph("Filing Information", section_style))
    info_data = [
        ["Filing Status:", filing_status],
    ]
    info_table = Table(info_data, colWidths=[2*inch, 5*inch])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 12))
    
    # Income Section
    elements.append(Paragraph("Income", section_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1e3a5f')))
    
    income_data = [
        ["Line", "Description", "Amount"],
        ["1", "Wages, salaries, tips (W-2 Box 1)", f"${tax_data.get('total_wages', 0):,.2f}"],
        ["2a", "Tax-exempt interest", "$0.00"],
        ["2b", "Taxable interest", f"${tax_data.get('total_interest', 0):,.2f}"],
        ["3a", "Qualified dividends", f"${tax_data.get('qualified_dividends', 0):,.2f}"],
        ["3b", "Ordinary dividends", f"${tax_data.get('total_dividends', 0):,.2f}"],
        ["4a", "IRA distributions", "$0.00"],
        ["4b", "Taxable IRA distributions", "$0.00"],
        ["5a", "Pensions and annuities", "$0.00"],
        ["5b", "Taxable pensions", "$0.00"],
        ["6a", "Social security benefits", "$0.00"],
        ["6b", "Taxable social security", "$0.00"],
        ["7", "Capital gain or (loss)", f"${tax_data.get('total_capital_gains', 0):,.2f}"],
        ["8", "Other income (Schedule 1)", f"${tax_data.get('total_other_income', 0):,.2f}"],
    ]
    
    total_income = (
        tax_data.get('total_wages', 0) +
        tax_data.get('total_interest', 0) +
        tax_data.get('total_dividends', 0) +
        tax_data.get('total_capital_gains', 0) +
        tax_data.get('total_other_income', 0) +
        tax_data.get('total_rental_income', 0) +
        tax_data.get('total_business_income', 0)
    )
    income_data.append(["9", "Total income (add lines 1-8)", f"${total_income:,.2f}"])
    
    income_table = Table(income_data, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    income_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a5f')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8f4f8')),
    ]))
    elements.append(income_table)
    elements.append(Spacer(1, 12))
    
    # Adjustments Section
    elements.append(Paragraph("Adjustments to Income", section_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1e3a5f')))
    
    hsa_deduction = tax_data.get('hsa_deduction', 0)
    se_tax_deduction = tax_data.get('self_employment_tax', 0) / 2  # Half of SE tax is deductible
    total_adjustments = hsa_deduction + se_tax_deduction
    
    adj_data = [
        ["Line", "Description", "Amount"],
        ["10", "Educator expenses", "$0.00"],
        ["11", "Health savings account deduction", f"${hsa_deduction:,.2f}"],
        ["12", "Deductible part of self-employment tax", f"${se_tax_deduction:,.2f}"],
        ["13", "Self-employed SEP, SIMPLE plans", "$0.00"],
        ["14", "Self-employed health insurance deduction", "$0.00"],
        ["15", "Student loan interest deduction", "$0.00"],
        ["16", "Total adjustments", f"${total_adjustments:,.2f}"],
    ]
    
    adj_table = Table(adj_data, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    adj_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a5f')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8f4f8')),
    ]))
    elements.append(adj_table)
    elements.append(Spacer(1, 8))
    
    # AGI
    agi = tax_data.get('adjusted_gross_income', 0)
    agi_data = [
        ["17", "Adjusted Gross Income (Line 9 minus Line 16)", f"${agi:,.2f}"],
    ]
    agi_table = Table(agi_data, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    agi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#d4edda')),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#28a745')),
    ]))
    elements.append(agi_table)
    elements.append(Spacer(1, 12))
    
    # Deductions Section  
    elements.append(Paragraph("Deductions", section_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1e3a5f')))
    
    standard_ded = tax_data.get('standard_deduction', 0)
    itemized_ded = tax_data.get('itemized_deductions', 0)
    total_ded = tax_data.get('total_deductions', 0)
    using_standard = total_ded == standard_ded
    
    ded_data = [
        ["Line", "Description", "Amount"],
        ["18", "Standard deduction OR itemized deductions", ""],
        ["", f"  Standard deduction {'(USED)' if using_standard else ''}", f"${standard_ded:,.2f}"],
        ["", f"  Itemized deductions {'(USED)' if not using_standard else ''}", f"${itemized_ded:,.2f}"],
        ["19", "Qualified business income deduction", "$0.00"],
        ["20", "Total deductions", f"${total_ded:,.2f}"],
    ]
    
    ded_table = Table(ded_data, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    ded_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a5f')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8f4f8')),
    ]))
    elements.append(ded_table)
    elements.append(Spacer(1, 12))
    
    # Tax Calculation Section
    elements.append(Paragraph("Tax and Credits", section_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1e3a5f')))
    
    taxable_income = tax_data.get('taxable_income', 0)
    total_tax = tax_data.get('total_tax', 0)
    se_tax = tax_data.get('self_employment_tax', 0)
    additional_medicare = tax_data.get('additional_medicare_tax', 0)
    
    tax_data_rows = [
        ["Line", "Description", "Amount"],
        ["21", "Taxable income (Line 17 minus Line 20)", f"${taxable_income:,.2f}"],
        ["22", "Tax (from tax tables/calculation)", f"${tax_data.get('income_tax', total_tax - se_tax - additional_medicare):,.2f}"],
        ["23", "Additional Medicare Tax", f"${additional_medicare:,.2f}"],
        ["24", "Self-employment tax", f"${se_tax:,.2f}"],
        ["25", "Total tax", f"${total_tax:,.2f}"],
    ]
    
    tax_table = Table(tax_data_rows, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    tax_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a5f')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#ffebee')),
    ]))
    elements.append(tax_table)
    elements.append(Spacer(1, 12))
    
    # Payments Section
    elements.append(Paragraph("Payments", section_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1e3a5f')))
    
    withholding = tax_data.get('total_withholding', 0)
    payments_data = [
        ["Line", "Description", "Amount"],
        ["26", "Federal income tax withheld (W-2 Box 2)", f"${withholding:,.2f}"],
        ["27", "Estimated tax payments", "$0.00"],
        ["28", "Earned income credit (EIC)", "$0.00"],
        ["29", "Additional child tax credit", "$0.00"],
        ["30", "Total payments", f"${withholding:,.2f}"],
    ]
    
    payments_table = Table(payments_data, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    payments_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a5f')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8f4f8')),
    ]))
    elements.append(payments_table)
    elements.append(Spacer(1, 12))
    
    # Refund/Amount Owed Section
    refund_or_owed = withholding - total_tax
    is_refund = refund_or_owed >= 0
    
    if is_refund:
        result_data = [
            ["31", "REFUND (Line 30 minus Line 25)", f"${refund_or_owed:,.2f}"],
        ]
        result_color = colors.HexColor('#28a745')
        bg_color = colors.HexColor('#d4edda')
    else:
        result_data = [
            ["31", "AMOUNT YOU OWE (Line 25 minus Line 30)", f"${abs(refund_or_owed):,.2f}"],
        ]
        result_color = colors.HexColor('#dc3545')
        bg_color = colors.HexColor('#f8d7da')
    
    result_table = Table(result_data, colWidths=[0.6*inch, 4.4*inch, 2*inch])
    result_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg_color),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOX', (0, 0), (-1, -1), 2, result_color),
        ('TEXTCOLOR', (0, 0), (-1, -1), result_color),
    ]))
    elements.append(result_table)
    elements.append(Spacer(1, 20))
    
    # Footer
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.gray))
    elements.append(Spacer(1, 8))
    footer_style = ParagraphStyle(
        'Footer',
        parent=normal_style,
        fontSize=8,
        textColor=colors.gray,
        alignment=TA_CENTER
    )
    elements.append(Paragraph(
        f"Generated by TaxSnapPro on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        footer_style
    ))
    elements.append(Paragraph(
        "This document is for informational and planning purposes only. "
        "It is not a substitute for professional tax advice and should not be filed with the IRS.",
        footer_style
    ))
    
    # Build PDF
    doc.build(elements)
    
    if output_path:
        return None
    else:
        buffer.seek(0)
        return buffer.getvalue()


def get_tax_data_from_state(state) -> Dict[str, Any]:
    """Extract tax data dictionary from state object."""
    return {
        'tax_year': getattr(state, 'tax_year', 2024),
        'filing_status': getattr(state, 'filing_status', 'single'),
        'total_wages': getattr(state, 'total_wages', 0),
        'total_interest': getattr(state, 'total_interest', 0),
        'total_dividends': getattr(state, 'total_dividends', 0),
        'qualified_dividends': getattr(state, 'qualified_dividends', 0),
        'total_capital_gains': getattr(state, 'total_capital_gains', 0),
        'total_other_income': getattr(state, 'total_other_income', 0),
        'total_rental_income': getattr(state, 'total_rental_income', 0),
        'total_business_income': getattr(state, 'total_business_income', 0),
        'hsa_deduction': getattr(state, 'hsa_deduction', 0),
        'self_employment_tax': getattr(state, 'self_employment_tax', 0),
        'adjusted_gross_income': getattr(state, 'adjusted_gross_income', 0),
        'standard_deduction': getattr(state, 'standard_deduction', 0),
        'itemized_deductions': getattr(state, 'itemized_deductions', 0),
        'total_deductions': getattr(state, 'total_deductions', 0),
        'taxable_income': getattr(state, 'taxable_income', 0),
        'total_tax': getattr(state, 'total_tax', 0),
        'additional_medicare_tax': getattr(state, 'additional_medicare_tax', 0),
        'total_withholding': getattr(state, 'total_withholding', 0),
    }
